### ISSUE TITLE
请问一下，ip:90可以访问ssh界面，但是直接ip访问是ubuntu网页服务器的默认文档

### ISSUE THREAD

**Issue by KevinGarrick7** [able8/pi-net#3]
系统使用的是orangepi官网提供的ubuntu server，板子使用的是orangepi win plus，有什么办法可以解决吗，谢谢

**Comment by able8** [comment]
说明80端口冲突了
要么把你系统里的web服务停掉，
要么修改/etc/rc.local 把里面的80改成其他端口
