### ISSUE TITLE
项目不能成功运行

### ISSUE THREAD

**Issue by px1396** [able8/pi-net#5]
你好，我git clone了您的项目，但在实际操作中并不能成功运行，问题如下；

1. 使用Armbian官网 Armbian Bionic mainline kernel 4.14.y镜像，安装pi-net项目后可以打开pi-net主页，但是无法配置双S，点击主页任何一个按钮后出现的都是空白页面。
2. 使用Armbian官网Armbian Stretch mainline kernel 4.14.y镜像，安装pi-net项目后查看日志，出现 ss-redir: error while loading shared libraries: libev.so.4: cannot open shared object file: No such file or directory

希望作者能给与指导，或者能分享一下自用的系统镜像，谢谢！

**Comment by able8** [comment]
我用的这个镜像 Armbian_5.38_Orangepizero_Ubuntu_xenial_next_4.14.14.img
